version: '3.3'

volumes:
  post_dbs:

networks:
  reddit:
  promit-net:

services:
  post_db:
    image: mongo:3.2
    container_name: post-db
    networks:
      promit-net:
        aliases:
          - post_db
          - comment_db
      reddit:
        aliases:
          - post_db
          - commment_db
    volumes:
      - ./post_dbs:/data/db

  post:
    image: ${USER_NAME}/post
    container_name: post
    restart: always
    networks:
      promit-net:
        aliases:
          - post
      reddit:
        aliases:
          - post

  comment:
    image: ${USER_NAME}/comment
    container_name: comment
    restart: always
    networks:
      promit-net:
        aliases:
          - comment
      reddit:
        aliases:
          - comment
    env_file: .env

  ui:
    image: ${USER_NAME}/ui
    container_name: ui
    restart: always
    networks:
      promit-net:
        aliases:
          - ui
      reddit:
        aliases:
          - ui
    ports:
      - 9292:9292
  
