version: '3.3'

volumes:
  post_dbs:
  prometheus_data:

networks:
  reddit:
  promit-net:

services:
  post_db:
    image: mongo:3.2
    container_name: post-db
    networks:
      promit-net:
        aliases:
          - post_db
          - comment_db
      reddit:
        aliases:
          - post_db
          - commment_db
    volumes:
      - ./post_dbs:/data/db

  post:
    image: ${USER_NAME}/post:latest
    container_name: post
    restart: always
    networks:
      promit-net:
        aliases:
          - post
      reddit:
        aliases:
          - post

  comment:
    image: ${USER_NAME}/comment:latest
    container_name: comment
    restart: always
    networks:
      promit-net:
        aliases:
          - comment
      reddit:
        aliases:
          - comment
    env_file: .env

  ui:
    image: ${USER_NAME}/ui:latest
    container_name: ui
    restart: always
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      promit-net:
        aliases:
          - ui
      reddit:
        aliases:
          - ui
    ports:
      - 9292:9292

  prometheus:
    image: ${USER_NAME}/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      promit-net:
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    restart: always
    networks:
      promit-net:
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  
